export const expertiseList = [
  { name: "General Dentistry" },
  { name: "Paediatric Dentistry" },
  { name: "Orthodontics" },
  { name: "Clear Aligners" },
  { name: "Endodontics" },
  { name: "Periodontics" },
  { name: "Prosthodontics" },
  { name: "Oral Surgery and Exodontia" },
  { name: "Maxillofacial Surgery" },
  { name: "Dental Pathology" },
  { name: "Dental Radiology" },
  { name: "Cosmetic Dentistry" },
  { name: "Geriatric Dentistry" },
  { name: "Special Needs Dentistry" },
  { name: "TMD Management" },
  { name: "Occlusion & Neuromuscular Dentistry" },
  { name: "Dental Sleep Medicine" },
  { name: "Laser Dentistry" },
  { name: "Implantology" },
  { name: "Restorative Dentistry" },
  { name: "Oral Medicine" },
  { name: "Dental Oncology" },
  { name: "Dental Pharmacology" },
  { name: "Dental Traumatology" },
  { name: "Sedation Dentistry" },
  { name: "Dental Hygiene" },
  { name: "Dental Nursing" },
  { name: "Dental Therapy" },
  { name: "Dental Technician" },
  { name: "Biomimetic Dentistry" },
  { name: "Dental Anaesthesiology" },
  { name: "Oral Microbiology" },
  { name: "Digital Dentistry" },
  { name: "CEREC and CAD/CAM Dentistry" },
  { name: "Composite" },
  { name: "Treatment Planning" },
  { name: "Veneers" },
  { name: "Facial Aesthetics" },
  { name: "Dental Public Health" },
  { name: "Dental Research" },
  { name: "Dental Education" },
  { name: "Overseas Registration" },
  { name: "Dental Practice Management" },
  { name: "Dental Law" },
  { name: "Dental Technology" },
  { name: "Dental Photography" },
  { name: "Dental Ergonomics" },
  { name: "Dental Ethics" },
  { name: "Dental Software" },
  { name: "Dental Practice Marketing" },
  { name: "Dental Lab Communication" },
  { name: "Dental Practice Transitions" },
  { name: "Dental Business" },
  { name: "Forensic Odontology" },
  { name: "Oral Health Epidemiology" },
  { name: "Dental Material Science" },
  { name: "Oral Health Promotion" },
  { name: "Mindset Coaching" },
  { name: "Ethical Selling" },
  { name: "Dental Practice Purchase" },
  { name: "Medical Emergencies and CPR" },
  { name: "Entrepreneurship" },
  { name: "Personal Development" },
];

export const mentorExpertise = [
  { id: 1, name: "Endodontist", years: 3 },
  { id: 2, name: "Orthodontist", years: 2 },
  { id: 3, name: "Periodontist", years: 5 },
];
